### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by alexchiu100014** [paul0728/KKUnusedModsRemoverPacker#1]
Traceback (most recent call last):
  File "KK_mod_remover_packer_mutilang.py", line 802, in <module>
  File "KK_mod_remover_packer_mutilang.py", line 798, in main
  File "KK_mod_remover_packer_mutilang.py", line 257, in __init__
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "E:\pythonwork\KKUnusedModsRemoverPacker\KK_unused_mods_remover_packer_icon.ico" not defined

Windows 11 Pro 23H2

![圖片](https://github.com/user-attachments/assets/ccda7a79-7a67-49ce-a932-948eef780021)

**Comment by paul0728** [comment]
這是icon無法正確讀取所造成，已解決並發布[新版](https://github.com/paul0728/KKUnusedModsRemoverPacker/releases/tag/v1.0)
